apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      template: application-template-stibuild
    name: dbsecret
  stringData:
    mysql-password: FAKE
    mysql-user: FAKE
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      template: application-template-stibuild
    name: frontend
  spec:
    ports:
    - name: web
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 8080
    selector:
      name: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    labels:
      template: application-template-stibuild
    name: route-edge
  spec:
    host: www.example.com
    tls:
      termination: edge
    to:
      kind: Service
      name: frontend
  status: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      template: application-template-stibuild
    name: origin-ruby-sample
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      template: application-template-stibuild
    name: ruby-25-centos7
  spec:
    dockerImageRepository: centos/ruby-25-centos7
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      name: ruby-sample-build
      template: application-template-stibuild
    name: ruby-sample-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: origin-ruby-sample:latest
    postCommit:
      script: bundle exec rake test
    resources: {}
    source:
      git:
        uri: https://github.com/openshift/ruby-hello-world.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: EXAMPLE
          value: sample-app
        from:
          kind: ImageStreamTag
          name: ruby-25-centos7:latest
      type: Source
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        allowEnv: true
        secret: secret101
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      template: application-template-stibuild
    name: frontend
  spec:
    replicas: 2
    selector:
      name: frontend
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        post:
          execNewPod:
            command:
            - /bin/true
            containerName: ruby-helloworld
            env:
            - name: CUSTOM_VAR2
              value: custom_value2
          failurePolicy: Ignore
        pre:
          execNewPod:
            command:
            - /bin/true
            containerName: ruby-helloworld
            env:
            - name: CUSTOM_VAR1
              value: custom_value1
          failurePolicy: Abort
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: frontend
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: mysql-user
                name: dbsecret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-password
                name: dbsecret
          - name: MYSQL_DATABASE
            value: root
          image: origin-ruby-sample
          imagePullPolicy: IfNotPresent
          name: ruby-helloworld
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ruby-helloworld
        from:
          kind: ImageStreamTag
          name: origin-ruby-sample:latest
      type: ImageChange
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      template: application-template-stibuild
    name: database
  spec:
    ports:
    - name: db
      nodePort: 0
      port: 5434
      protocol: TCP
      targetPort: 3306
    selector:
      name: database
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      template: application-template-stibuild
    name: database
  spec:
    replicas: 1
    selector:
      name: database
    strategy:
      recreateParams:
        mid:
          execNewPod:
            command:
            - /bin/true
            containerName: ruby-helloworld-database
            env:
            - name: CUSTOM_VAR2
              value: custom_value2
            volumes:
            - ruby-helloworld-data
          failurePolicy: Abort
        post:
          execNewPod:
            command:
            - /bin/true
            containerName: ruby-helloworld-database
            env:
            - name: CUSTOM_VAR2
              value: custom_value2
            volumes:
            - ruby-helloworld-data
          failurePolicy: Ignore
        pre:
          execNewPod:
            command:
            - /bin/true
            containerName: ruby-helloworld-database
            env:
            - name: CUSTOM_VAR1
              value: custom_value1
            volumes:
            - ruby-helloworld-data
          failurePolicy: Abort
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          name: database
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: mysql-user
                name: dbsecret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-password
                name: dbsecret
          - name: MYSQL_DATABASE
            value: root
          image: centos/mysql-57-centos7:latest
          imagePullPolicy: Always
          name: ruby-helloworld-database
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ruby-helloworld-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ""
          name: ruby-helloworld-data
    triggers:
    - type: ConfigChange
  status: {}
kind: List
metadata: {}
